title: Kunang Kunang
email: your-email@example.com
description: >-
  Kunang-Kunang adalah sebuah komunitas yang peduli terhadap masalah kesehatan, khususnya kesehatan remaja.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
name: Kunang Kunang
twitter_username: jekyllrb
github_username:  jekyll
whatsapp: +6212345678

bitrix_contact_embed_code: >
  <script id="bx24_form_inline" data-skip-moving="true">
          (function(w,d,u,b){w['Bitrix24FormObject']=b;w[b] = w[b] || function(){arguments[0].ref=u;
                  (w[b].forms=w[b].forms||[]).push(arguments[0])};
                  if(w[b]['forms']) return;
                  var s=d.createElement('script');s.async=1;s.src=u+'?'+(1*new Date());
                  var h=d.getElementsByTagName('script')[0];h.parentNode.insertBefore(s,h);
          })(window,document,'https://b24-ckw11l.bitrix24.com/bitrix/js/crm/form_loader.js','b24form');

          b24form({"id":"2","lang":"en","sec":"07rggy","type":"inline"});
  </script>

bitrix_contact_sec: >
  your-sect

bitrix_chat_embed: >
  <script data-skip-moving="true">
          (function(w,d,u){
                  var s=d.createElement('script');s.async=1;s.src=u+'?'+(Date.now()/60000|0);
                  var h=d.getElementsByTagName('script')[0];h.parentNode.insertBefore(s,h);
          })(window,document,'https://cdn.bitrix24.com/b5850365/crm/site_button/loader_6_raubd8.js');
  </script>


# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
sass:
  load_paths:
    - node_modules
    - assets
  sass_dir: node_modules
exclude:
  - assets/*.sass
  - assets/*.es6
  - yarn.lock
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - packages.json
  - '*.sh'

# <script id="bx24_form_inline" data-skip-moving="true">
#         (function(w,d,u,b){w['Bitrix24FormObject']=b;w[b] = w[b] || function(){arguments[0].ref=u;
#                 (w[b].forms=w[b].forms||[]).push(arguments[0])};
#                 if(w[b]['forms']) return;
#                 var s=d.createElement('script');s.async=1;s.src=u+'?'+(1*new Date());
#                 var h=d.getElementsByTagName('script')[0];h.parentNode.insertBefore(s,h);
#         })(window,document,'https://your-bitrix-url.bitrix24.com/bitrix/js/crm/form_loader.js','b24form');
# 
#         b24form({"id":"4","lang":"en","sec":"your-form-sec-code","type":"inline"});
# </script>
